### ISSUE TITLE
Multiple language support for naming files and folders

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/agsbs_atom_package#280]
At the moment the package looks for files in the folder **bilder** (engl. images) and **tabellen** (engl. tables) if they are inserted via gui. 

### ToDos

- [ ] check the defined language in *.lecturemetadata.dcxml*
- [ ] file names in supported languages:
     - [ ] bilder.md
     - [ ] names if chapters, e.g. k01.md
- [ ] support for following languages:
     - [ ] German
     - [ ] English
     - [ ] French
     - [ ] Spanish

**Comment by jevo** [comment]
This issue requires changes in matuc because Atom only parse the returned string of matuc.
Matuc also checks the structure and generates the files.

See the issue also in matuc https://github.com/TUD-INF-IAI-MCI/AGSBS-infrastructure/issues/42 and https://github.com/TUD-INF-IAI-MCI/AGSBS-infrastructure/issues/51
